services:
  - type: web
    name: mrbeast-video-clipper
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app
